Tmall/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('df_user.urls_df_user')),
    path('', include('df_goods.urls_df_goods')),
    path('cart/', include('df_cart.urls_cart')),
    path('order/', include('df_order.urls_order')),
]

df_order/models.py
from django.db import models


class Order(models.Model):
    user = models.ForeignKey('df_user.UserInfo', on_delete=models.CASCADE, verbose_name='收货人')
    address = models.CharField(max_length=100, verbose_name='收货人地址')
    datetime = models.DateTimeField(auto_now_add=True, verbose_name='提交订单时间')
    is_paid = models.BooleanField(default=False, verbose_name='是否已付钱')
    total = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='总价')

    def __str__(self):
        return '{}在{}提交的订单'.format(self.user.username, self.datetime)

    class Meta:
        verbose_name = verbose_name_plural = '订单'


class OrderDetail(models.Model):
    price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='商品价格')
    count = models.IntegerField(verbose_name='商品数量')
    goods = models.ForeignKey('df_goods.GoodsInfo', on_delete=models.CASCADE, verbose_name='商品')
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='订单')

    def __str__(self):
        # return self.goods.title + "(数量为" + str(self.count)  + ")"
        return "{0}(数量为{1})".format(self.goods.title, self.count)

    class Meta:
        verbose_name = verbose_name_plural = '订单详情'

df_user/models.py
from django.db import models


class UserInfo(models.Model):
    username = models.CharField(max_length=20, verbose_name='昵称')
    password = models.CharField(max_length=40, verbose_name='密码')
    email = models.CharField(max_length=30, verbose_name='邮箱')
    full_name = models.CharField(max_length=20, default='', verbose_name='姓名')
    address = models.CharField(max_length=100, default='', verbose_name='地址')
    postcode = models.CharField(max_length=6, default='', verbose_name='邮编')
    phone = models.CharField(max_length=11, default='', verbose_name='手机')
    # default, blank 是 python 层面的约束，不影响表结构

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = '用户'
        verbose_name = '用户'

df_user/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import JsonResponse
from django.core.paginator import Paginator
from hashlib import sha1
from . import models
from . import user_decorator
from df_goods.models import GoodsInfo
from df_order.models import Order

NUM_ORDER = 2


def register(request):
    return render(request, 'df_user/register.html')


def register_handle(request):
    # 接收用户输入
    post_get = request.POST.get
    user_name = post_get('user_name')
    pwd = post_get('pwd')
    pwd2 = post_get('cpwd')
    email = post_get('email')

    # 判断两次密码
    if pwd != pwd2:
        return redirect('df_user:register')

    # 密码加密
    epwd = sha1()
    epwd.update(pwd.encode("UTF-8"))  # 参数必须为bytes类型，encode返回编码后的字符串，它是一个 bytes 对象。
    pwd = epwd.hexdigest()

    # 创建对象
    models.UserInfo.objects.create(username=user_name, password=pwd, email=email)

    # 注册成功，转到登录页面
    return redirect('df_user:login')


# 判断用户名是否已存在
def register_exit(request):
    username = request.GET.get('username')
    count = models.UserInfo.objects.filter(username=username).count()
    return JsonResponse({'count': count})


def login(request):
    username = request.COOKIES.get('username', '')  # 填错后再填可以复现
    context = {
        'username': username,
        'error_name': '0',
        'error_pwd': '0',
    }
    return render(request, 'df_user/login.html', context)


def login_handle(request):
    # 接收请求信息
    user_name = request.POST.get('user_name')
    password = request.POST.get('pwd')
    jizhu = request.POST.get('jizhu', 0)
    # 根据用户名查询对象
    users = models.UserInfo.objects.filter(username=user_name)
    if users:
        epwd = sha1()
        epwd.update(password.encode('utf8'))
        if epwd.hexdigest() == users[0].password:
            url = request.COOKIES.get('url', '/goods/index/')  # 记录之前的url，如果没有记录则设置为商品首页
            red = HttpResponseRedirect(url)  # 用变量记住,方便设置cookie
            # 记住用户名
            if jizhu:
                red.set_cookie('username', user_name)  # 设置cookie保存用户名
            else:
                red.set_cookie('username', '', max_age=-1)  # max_age指的是过期时间,当为-1时为立刻过期
            request.session['user_id'] = users[0].id  # 把用户id和名字放入session中
            request.session['user_name'] = user_name
            return red
        else:
            context = {
                'username': user_name,
                'password': password,
                'error_name': 0,
                'error_pwd': 1,
            }
            return render(request, 'df_user/login.html', context)
    else:
        context = {
            'username': user_name,
            'password': password,
            'error_name': 1,
            'error_pwd': 0,
        }
        return render(request, 'df_user/login.html', context)


@user_decorator.login
def info(request):
    user_id = request.session['user_id']
    user = models.UserInfo.objects.get(id=user_id)
    user_phone = user.phone
    user_site = user.address
    user_full_name = user.full_name
    goods_ids = request.COOKIES.get('goods_ids', '')
    goods_ids1 = goods_ids.split(',')
    goods_list = []
    for goods_id in goods_ids1:
        if goods_id:
            goods_list.append((GoodsInfo.objects.get(id=int(goods_id))))
    context = {
        'title': '用户中心',
        'user_name': request.session['user_name'],
        'user_full_name': user_full_name,
        'user_phone': user_phone,
        'user_site': user_site,
        'goods_list': goods_list,
    }
    return render(request, 'df_user/user_center_info.html', context)


@user_decorator.login
def order(request, page_id=1):
    user_id = request.session['user_id']
    orders_list = Order.objects.filter(user_id=user_id).order_by('id')
    if orders_list:
        pages = Paginator(orders_list, NUM_ORDER)
        page = pages.page(page_id)
    else:
        pages = page = 0
    context = {
        'title': '全部订单',
        'pages': pages,
        'page': page,
    }
    return render(request, 'df_user/user_center_order.html', context)


@user_decorator.login
def site(request):
    user = models.UserInfo.objects.get(id=request.session['user_id'])
    if request.method == 'POST':
        post_get = request.POST.get
        user.full_name = post_get('full_name')
        user.address = post_get('address')
        user.postcode = post_get('postcode')
        user.phone = post_get('phone')
        user.save()
    context = {
        'title': '收货地址',
        'user': user,
    }
    return render(request, 'df_user/user_center_site.html', context)


def logout(request):
    request.session.flush()
    return redirect(reversed('df_goods:index'))

df_user/templates/df_user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}用户登录{% endblock %}

{% block css %}
    <script>
        $(function () {
            name_error = 0;
            pwd_error = 0;

            if ({{error_name}}) {
                $('.user_error').html('用户名错误').show();
            }

            if ({{error_pwd}}) {
                $('.pwd_error').html('密码错误').show();
            }

            $('.name_input').blur(function () {
                if ($('.name_input').val().length === 0) {
                    $('.user_error').html('请填写用户名').show();
                    name_error = 0
                } else {
                    $('.user_error').hide();
                    name_error = 1;
                }
            });

            $('.pass_input').blur(function () {
                if ($('.pass_input').val().length === 0) {
                    $('.pwd_error').html('请输入密码').show();
                    pwd_error = 0;
                } else {
                    $('.pwd_error').hide();
                    pwd_error = 1;
                }
            });
        });
    </script>
{% endblock %}

{% block nav %}{% endblock %}

{% block search %}{% endblock %}

{% block content %}
    <div class="login_top clearfix">
        <a href="{% url 'df_goods:index' %}" class="login_logo"><img alt="天天生鲜" src="/static/images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'df_user:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'df_user:login_handle' %}" method="post">
                        {% csrf_token %}
                        <input type="text" name="user_name" class="name_input" value="{{ username }}"
                               placeholder="请输入用户名">
                        <div class="user_error">输入错误</div>

                        <input type="password" name="pwd" class="pass_input" value="{{ password }}" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>

                        <div class="more_input clearfix">
                            <input type="checkbox" name="jizhu" value="1" id="checkbox" checked="checked">
                            <label for="checkbox">记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

df_user/templates/df_user/register.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}用户注册{% endblock %}

{% block css %}
    <script src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block nav %}{% endblock %}

{% block content %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img alt="天天生鲜" src="{% static 'images/logo02.png' %}"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="{% url 'df_user:login' %}">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form action="{% url 'df_user:register_handle' %}" method="post">

                    {% csrf_token %}

                    <ul>
                        <li>
                            <label for="user_name">用户名:</label>
                            {# name属性用于后端，id属性用户前端，尽量二者设置同一个名字 #}
                            <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label for="pwd">密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label for="cpwd">确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label for="email">邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label for="allow">同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册">
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

df_user/templates/df_user/user_center_info.html
{% extends 'base.html' %}

{% block title %}天天生鲜-{{ title }}{% endblock %}

{% block content %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'df_user:info' %}" class="active">· 个人信息</a></li>
                <li><a href="{% url 'df_user:order' 1 %}">· 全部订单</a></li>
                <li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ user_name }}</li>
                    <li><span>收货人：</span>{{ user_full_name }}</li>
                    <li><span>联系电话：</span>{{ user_phone }}</li>
                    <li><span>联系地址：</span>{{ user_site }}</li>
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {% for goods in goods_list %}
                        <li>
                            <a href="{% url 'df_goods:good_detail' goods.id %}"><img alt="图片"
                                                                                     src="/static/{{ goods.pic }}/"></a>
                            <h4><a href="{% url 'df_goods:good_detail' goods.id %}">{{ goods.title }}</a></h4>
                            <div class="operate">
                                <span class="prize">{{ goods.price }}</span>
                                <span class="unit">{{ goods.price }}/{{ goods.unit }}</span>
                                <a href="{% url 'df_cart:add' goods.id 1 %}" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

df_user/templates/df_user/user_center_order.html
{% extends 'base.html' %}

{% block title %}天天生鲜-{{ title }}{% endblock %}

{% block content %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'df_user:info' %}">· 个人信息</a></li>
                <li><a href="{% url 'df_user:order' 1 %}" class="active">· 全部订单</a></li>
                <li><a href="{% url 'df_user:site' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
        {% if pages %}
            {% for order in page %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01" style="text-align: left">{{ order.datetime }}</li>
                    <li class="col02" style="text-align: center">{{ order.address }}</li>
                    <li class="col03 stress" style="text-align: right">未支付</li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="55%">
                            {% for order_detail in order.orderdetail_set.all %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img alt="商品图片" src="/static/{{ order_detail.goods.pic }}">
                                    </li>
                                    <li class="col02">{{ order_detail.goods.title }}<em>{{ order_detail.price }}/{{ order_detail.goods.unit }}</em>
                                    </li>
                                    <li class="col03">{{ order_detail.count }}</li>
                                    <li class="col04">运费：￥10</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total }}</td>
                        <td width="15%">待付款</td>
                        <td width="15%"><a href="{% url 'df_order:pay' order.id %}" class="oper_btn">去付款</a></td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
        {% else %}
            <p>暂无订单</p>
        {% endif %}
            <div class="pagenation">
            {% if pages %}
                {% if page.has_previous %}
                    <a href="{% url "df_user:order" page.previous_page_number %}">上一页</a>
                {% endif %}

                {% for page_index in pages.page_range %}
                    {% if page_index == page.number %}
                        <a href="" class="active">{{ page_index }}</a>
                    {% else %}
                        <a href="{% url "df_user:order" page_index %}">{{ page_index }}</a>
                    {% endif %}
                {% endfor %}

                {% if page.has_next %}
                    <a href="{% url "df_user:order" page.next_page_number %}">下一页</a>
                {% endif %}
            {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

df_user/templates/df_user/user_center_site.html
{% extends 'base.html' %}

{% block title %}天天生鲜-{{ title }}{% endblock %}

{% block content %}

    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'df_user:info' %}">· 个人信息</a></li>
                <li><a href="{% url 'df_user:order' 1 %}">· 全部订单</a></li>
                <li><a href="{% url 'df_user:site' %}" class="active">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">收货地址</h3>
            <div class="site_con">
                <dl>
                    <dt>当前地址：</dt>
                    <dd>{{ user.address }}&nbsp;&nbsp;({{ user.full_name }})&nbsp;&nbsp;{{ user.phone }}</dd>
                </dl>
            </div>
            <h3 class="common_title2">编辑地址</h3>
            <div class="site_con">
                <form action="{% url 'df_user:site' %}" method="post">
                    {% csrf_token %}
                    <div class="form_group">
                        <label for="full_name">收件人：</label>
                        <input type="text" name="full_name" id="full_name" value="{{ user.full_name }}">
                    </div>
                    <div class="form_group form_group2">
                        <label for="address">详细地址：</label>
                        <textarea class="site_area" name="address" id="address">{{ user.address }}</textarea>
                    </div>
                    <div class="form_group">
                        <label for="postcode">邮编：</label>
                        <input type="text" name="postcode" id="postcode" value="{{ user.postcode }}">
                    </div>
                    <div class="form_group">
                        <label for="phone">手机：</label>
                        <input type="text" name="phone" id="phone" value="{{ user.phone }}">
                    </div>

                    <input type="submit" value="提交" class="info_submit">
                </form>
            </div>
        </div>
    </div>

{% endblock %}